version: '3'
services:
  nginx:
   container_name: openCredit-nginx
   image: nginx:1.13
   restart: always
   ports:
    - 80:80
    - 443:443
   volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
   depends_on:
    - app
 
  mysql:
   container_name: opencredit-mysql
   image: mysql/mysql-server:5.7
   environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=spring_app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=test123
   expose:
    - "3306"
   restart: always
  
  app:
    container_name: opencredit-app
    restart: always
    build: ./spring-boot-starter
    volumes:
      - ./spring-boot-starter:/app
    command:
      ["java", "-cp", "conf/:apps/*:lib/*", "-jar", "/app/dist/apps/openCredit.jar"]
    expose:
      - "8080"
    depends_on:
      - mysql